# Generated by Django 3.2.9 on 2021-12-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='car_plate',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
