# Generated by Django 3.2.9 on 2021-12-12 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_location_parkinglot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='parking_lots',
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.location'),
        ),
    ]
