# Generated by Django 3.2.9 on 2021-12-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_auto_20211212_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='car_type',
            field=models.CharField(choices=[('SALOON', 'SALOON'), ('HEAVY DUTY', 'HEAVY DUTY'), ('SUV', 'SUV')], max_length=100),
        ),
    ]
