# Generated by Django 3.2.9 on 2021-12-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_alter_vehicle_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
